# Generated by Django 6.0.5 on 2026-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='image',
        ),
        migrations.AddField(
            model_name='identification',
            name='family_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='tamil_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='ai_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='confidence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
