# Generated by Django 6.0.5 on 2026-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0002_remove_identification_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organisms/'),
        ),
    ]
