# Generated by Django 6.0.5 on 2026-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0003_identification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='organism_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='wikipedia_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
